name: veevo_connect
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  font_awesome_flutter_named: ^1.1.1+4
  dynamic_fa_icons: ^1.1.0+2
 # font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
#
#    fonts:
#      - family: AppIcons
#        fonts:
#          - asset: assets/icons/AppIcons.ttf
#  #
#  #    - family: Mulish
#  #      fonts:
#  #        - asset: assets/fonts/Mulish-Black.ttf

